### PR TITLE
chore(fix): add in missing backups methods

### LINKED ISSUE #2939: master branch is missing a couple of backup methods
While porting the backups api to the master branch, I think we lost 2 methods on BigtableTableAdminGrpcClient:
- getBackupAsync
-  updateBackupAsync

Customers might be using those methods directly in bigtable-client-core so we cant remove them

### PR DESCRIPTION
**Pull request by kolea2**
Fixes #2939

### CODE REVIEW

File: bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableTableAdminGrpcClient.java [hunk 1]
```diff
@@ -21,24 +21,7 @@
...
-import com.google.bigtable.admin.v2.GenerateConsistencyTokenResponse;
-import com.google.bigtable.admin.v2.GetTableRequest;
-import com.google.bigtable.admin.v2.ListBackupsRequest;
-import com.google.bigtable.admin.v2.ListBackupsResponse;
-import com.google.bigtable.admin.v2.ListTablesRequest;
-import com.google.bigtable.admin.v2.ListTablesResponse;
-import com.google.bigtable.admin.v2.ModifyColumnFamiliesRequest;
-import com.google.bigtable.admin.v2.RestoreTableRequest;
-import com.google.bigtable.admin.v2.Table;
+import com.google.bigtable.admin.v2.*;
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableTableAdminGrpcClient.java:24]: please dot use glob imports

File: bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/TestBigtableTableAdminGrpcClient.java [hunk 2]
```diff
@@ -22,19 +22,7 @@
...
-import com.google.bigtable.admin.v2.DeleteBackupRequest;
-import com.google.bigtable.admin.v2.DropRowRangeRequest;
-import com.google.bigtable.admin.v2.GenerateConsistencyTokenRequest;
-import com.google.bigtable.admin.v2.GenerateConsistencyTokenResponse;
-import com.google.bigtable.admin.v2.GetTableRequest;
-import com.google.bigtable.admin.v2.ListBackupsRequest;
-import com.google.bigtable.admin.v2.ModifyColumnFamiliesRequest;
-import com.google.bigtable.admin.v2.RestoreTableRequest;
-import com.google.bigtable.admin.v2.Table;
+import com.google.bigtable.admin.v2.*;
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/TestBigtableTableAdminGrpcClient.java:25]: please dont use glob imports

**Review by igorbernstein2 — CHANGES_REQUESTED** [review]
lgtm, after the style fixes

**Review by igorbernstein2 — APPROVED** [review]
lgtm
