### PR TITLE
fix: qualifier filter comparators

### LINKED ISSUE #2672: hbase-2.x QualifierFilter / BinaryComparator broken for GREATER, GREATER_OR_EQUAL, LESS, LESS_OR_EQUAL
#### Environment details

1. Specify the API at the beginning of the title. General, Core, and Other are also allowed as types
2. OS type and version: Linux / OSX
3. Java version: 1.8
4. Version(s): hbase-2.x / bt client 1.16

#### Steps to reproduce

Run the test below on both HBase and BT 

#### Code example

```java
@Test
  void binaryComparatorIsBroken() throws IOException {
    Table table = <get your table instance>
    byte[] row = toBytes("a");
    Put put = new Put(row);
    byte[] family = toBytes("f");
    byte[] qualifier = toBytes(10);
    byte[] value = toBytes("value");
    put.addColumn(family, qualifier, value);
    table.put(put);

    byte[] prefix = toBytes(9);
    BinaryComparator filterComparator = new BinaryComparator(prefix);
    Filter filter = new QualifierFilter(CompareOperator.GREATER_OR_EQUAL, filterComparator);

    Get get = new Get(row);
    get.addFamily(family);
    get.setFilter(filter);

    Result result = table.get(get);
    assertThat(result.getValue(family, qualifier)).isEqualTo(value);
  }

#### Any additional information below


`GREATER`, `GREATER_OR_EQUAL` don't return any results when correctly set
`LESS`, `LESS_OR_EQUAL` don't filter anything, return results even when they shouldn't

### PR DESCRIPTION
**Pull request by kolea2**
Fixes #2672 ☕️

Also some refactoring to clean up helper methods in QualifierFilterAdapter

### CODE REVIEW

File: bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java [hunk 1]
```diff
@@ -1887,6 +1887,84 @@ public void testQualifierFilter() throws IOException {
...
+
+    Filter noOpFilter = new QualifierFilter(CompareOp.NO_OP, binaryComparator);
+    Get noOpGet = new Get(rowKey).setFilter(noOpFilter).addFamily(COLUMN_FAMILY);
+    Result noOpResult = table.get(noOpGet);
+    Assert.assertEquals(10, noOpResult.size());
+
+    table.close();
+  }
+
+  private void assertResult(Cell[] cells, int qualifierValue) {
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java:1961]: nit: assertCellQualifiersAreAscendingFrom (or something similar

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/QualifierFilterAdapter.java [hunk 2]
```diff
@@ -64,25 +63,39 @@ public Filter adapt(FilterAdapterContext context, QualifierFilter filter) throws
   private Filter adaptBinaryComparator(
       FilterAdapterContext context, CompareOp compareOp, BinaryComparator comparator)
       throws IOException {
-    ByteString quotedValue = ReaderExpressionHelper.quoteRegularExpression(comparator.getValue());
+    ByteString quotedValue = ByteString.copyFrom(comparator.getValue());
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/QualifierFilterAdapter.java:66]: ByteString value...its not quoted anymore

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/QualifierFilterAdapter.java [hunk 3]
```diff
@@ -64,25 +63,39 @@ public Filter adapt(FilterAdapterContext context, QualifierFilter filter) throws
   private Filter adaptBinaryComparator(
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/QualifierFilterAdapter.java:63]: Would you mind adding a bit of doc here for the future?

Something along the lines of:
Handles conversion of HBase's binary comparators to Bigtable's filters. Inequalities are implemented as ColumnRange filters, while EQUALS is implemented as a literal column_qualifier_regex_filter

**Review by igorbernstein2 — APPROVED** [review]
LGTM except for the nits
