### PR TITLE
fix: Add timeout to bulkMutation's close()

### LINKED ISSUE #4139: finishBundle() should timeout after a long time
I observe occasional hang in finishBundle() step for batch writes. Root cause unknown, but we should add timeout as a mitigation to prevent job from hanging forever.

### PR DESCRIPTION
**Pull request by kongweihan**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable-hbase/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #4139 ☕️

### CODE REVIEW

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/BulkMutationVeneerApi.java [hunk 1]
```diff
@@ -34,8 +37,17 @@ public class BulkMutationVeneerApi implements BulkMutationWrapper {
       BigtableClientMetrics.meter(MetricLevel.Info, "bulk-mutator.mutations.added");
   private final Batcher<RowMutationEntry, Void> bulkMutateBatcher;
 
+  private final long closeTimeoutSeconds; // If set to non-positive, never time out.
```
Comment (mutianf) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/BulkMutationVeneerApi.java:40]: Maybe move this comment to the constant definition

Comment (mutianf) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/BulkMutationVeneerApi.java:40]: I think we should make this > 0 = set timeout, 0 = disabled, < 0 is not allowed. And set a precondition check in BigtableHbaseVeneerSettings.

File: bigtable-dataflow-parent/bigtable-hbase-beam/src/test/java/com/google/cloud/bigtable/beam/FinishBundleTimeoutTest.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+
+public class FinishBundleTimeoutTest {
+
+  @Rule public TestPipeline writePipeline = TestPipeline.create();
+
+  @Rule public final TemporaryFolder workDir = new TemporaryFolder();
+
+  @Rule public ExpectedException thrown = ExpectedException.none();
+
+  @Test
```
Comment (mutianf) [inline bigtable-dataflow-parent/bigtable-hbase-beam/src/test/java/com/google/cloud/bigtable/beam/FinishBundleTimeoutTest.java:49]: lets set a timeout of 20 seconds on this test.  `@Test(timeout = 20)`

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java [hunk 3]
```diff
@@ -52,6 +52,11 @@ public BulkMutationWrapper createBulkMutation(String tableId) {
     return delegate.createBulkMutation(tableId);
```
Comment (mutianf) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java:52]: return createBulkMutation(tableId, 0);

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java [hunk 4]
```diff
@@ -78,16 +78,18 @@ public class BigtableBufferedMutatorHelper {
   public BigtableBufferedMutatorHelper(
       BigtableApi bigtableApi, BigtableHBaseSettings settings, HBaseRequestAdapter adapter) {
     this.adapter = adapter;
-    this.settings = settings;
+    this.settings =
+        settings; // this settings should have all the configs from CloudBigtableTableConfiguration
```
Comment (mutianf) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java:82]: I think we should remove this comment here. CloudBigtableTableConfiguration is only relevant to dataflow. Adding the comment here feels like we only use bufferedMutator for dataflow which is not true.

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/DataClientVeneerApi.java [hunk 5]
```diff
@@ -75,6 +75,11 @@ public BulkMutationWrapper createBulkMutation(String tableId) {
     return new BulkMutationVeneerApi(delegate.newBulkMutationBatcher(tableId));
```
Comment (mutianf) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/DataClientVeneerApi.java:75]: here call `new BulkMutationVeneerApi(deleget.newBulkMutationBatcher(tableId), 0)`.

**Review by mutianf — CHANGES_REQUESTED** [review]

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java (hunk 4 above)
Comment (kongweihan) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java:82]: ok. But just curious what else this is designed for?

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java [hunk 6]
```diff
@@ -51,6 +56,9 @@ public BigtableHBaseSettings(Configuration configuration) {
         configuration.getInt(
             BigtableOptionsFactory.BIGTABLE_SNAPSHOT_DEFAULT_TTL_SECS_KEY,
             BigtableOptionsFactory.BIGTABLE_SNAPSHOT_DEFAULT_TTL_SECS_VALUE);
+
+    this.bulkMutationCloseTimeoutSeconds =
+        configuration.getLong(BULK_MUTATION_CLOSE_TIMEOUT_SECONDS, 600);
```
[the remark this answers is not in the document]
Comment (kongweihan) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java:61]: In case the user sets a large operation timeout?
Even if we use it, should it longer than the operation timeout?

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java (hunk 4 above)
Comment (mutianf) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java]: It implements hbase buffered mutator: https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/BufferedMutator.html for batching requests, which are not always coming from dataflow

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java (hunk 3 above)
Comment (mutianf) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java:52]: I think it's cleaner when all the code goes through a single entry point when creating the object. https://stackoverflow.com/questions/581873/best-way-to-handle-multiple-constructors-in-java

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java [hunk 7]
```diff
@@ -39,6 +39,14 @@ public abstract class BigtableHBaseSettings {
   private final String instanceId;
   private final int ttlSecondsForBackup;
 
+  public static final String BULK_MUTATION_CLOSE_TIMEOUT_SECONDS =
+      "bulk.mutation.close.timeout.seconds";
+
+  // Must be non-negative. Set to 0 to disable timeout.
+  private final long bulkMutationCloseTimeoutSeconds;
+
+  private static final long DEFAULT_BULK_MUTATION_CLOSE_TIMEOUT_SECONDS = 600;
```
Comment (mutianf) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java:48]: Do we always want to force close the BufferedMutator, even when it's not used in dataflow? If not, we should set the default to 0, and in CloudBigtableConfiguration override it to 10 miutes.

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java (hunk 3 above)
Comment (kongweihan) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java:52]: IIUC this stackoverflow question is saying different ctors should all call the same ctor? It didn't say we should only have 1 ctor.

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java (hunk 4 above)
Comment (kongweihan) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java]: oh ok, so in hbase this is a separate class for batch mutation? Like it's not part of the regular hbase client?
Why do people have to create separate things for it instead of just adding the function to the client?

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java (hunk 7 above)
Comment (kongweihan) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java]: You're right. Updated

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java (hunk 4 above)
Comment (mutianf) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java]: Sorry, not sure I follow. BufferedMutator is the hbase equivalent of our batcher

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/DataClientVeneerApi.java [hunk 8]
```diff
@@ -72,7 +72,12 @@ public class DataClientVeneerApi implements DataClientWrapper {
 
   @Override
   public BulkMutationWrapper createBulkMutation(String tableId) {
-    return new BulkMutationVeneerApi(delegate.newBulkMutationBatcher(tableId));
+    return new BulkMutationVeneerApi(delegate.newBulkMutationBatcher(tableId), 0);
```
Comment (mutianf) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/DataClientVeneerApi.java:75]: Sorry, one more nit, here you can also call `return createBulkMutation(tableId, 0);`

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java (hunk 3 above)
Comment (mutianf) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/veneer/SharedDataClientWrapper.java:52]: I guess it doesn't matter too much

File: bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableConfiguration.java [hunk 9]
```diff
@@ -247,6 +248,15 @@ public Configuration toHBaseConfig() {
       }
     }
     setUserAgent(config);
+
+    ValueProvider<String> timeout =
+        configuration.get(BigtableHBaseSettings.BULK_MUTATION_CLOSE_TIMEOUT_SECONDS);
+    if (timeout == null) {
+      config.set(BigtableHBaseSettings.BULK_MUTATION_CLOSE_TIMEOUT_SECONDS, "600");
+    } else {
+      config.set(BigtableHBaseSettings.BULK_MUTATION_CLOSE_TIMEOUT_SECONDS, timeout.get());
```
Comment (mutianf) [inline bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableConfiguration.java:257]: I don't think we need to use value provider here for timeout, and also we can't call valueProvider.get() at this point (even though in this case it won't throw error) because this is called at graph construction time. Value provider (RuntimeValueProvider more specificlly) is used in dataflow templates to defer the get of the parameters. I found some more explanation of ValueProvider here: https://stackoverflow.com/questions/62948039/google-dataflow-and-apache-beam-why-valueprovider.

I know you probably followed examples from project id etc. However those examples are bad 😂  and we should avoid making the same mistake here (even though it won't throw error). When we're constructing the pipeline, we don't call `getProjectId` etc, instead we need to call the `getProjectIdValueProvider` version. See https://github.com/googleapis/java-bigtable-hbase/blob/main/bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableIO.java#L421-L424.

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java (hunk 4 above)
Comment (kongweihan) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableBufferedMutatorHelper.java]: no worries I just wondered why the batcher needs to be a separate class, why not adding the batching logic to the client directly.

File: bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableConfiguration.java (hunk 9 above)
Comment (mutianf) [reply bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableConfiguration.java:257]: nvm i was wrong. this is called at runtime. so we should be good

File: bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/TemplateUtils.java [hunk 10]
```diff
@@ -44,7 +44,8 @@ public static CloudBigtableTableConfiguration buildImportConfig(
             .withProjectId(opts.getBigtableProject())
             .withInstanceId(opts.getBigtableInstanceId())
             .withTableId(opts.getBigtableTableId())
-            .withConfiguration(BigtableOptionsFactory.CUSTOM_USER_AGENT_KEY, customUserAgent);
+            .withConfiguration(BigtableOptionsFactory.CUSTOM_USER_AGENT_KEY, customUserAgent)
+            .withConfiguration(BigtableOptionsFactory.BIGTABLE_MUTATE_RPC_TIMEOUT_MS_KEY, "600000");
```
Comment (mutianf) [inline bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/TemplateUtils.java:48]: revert this change?

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java [hunk 11]
```diff
@@ -39,6 +39,12 @@ public abstract class BigtableHBaseSettings {
   private final String instanceId;
   private final int ttlSecondsForBackup;
 
+  public static final String BULK_MUTATION_CLOSE_TIMEOUT_MILLISECONDS =
```
Comment (mutianf) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/wrappers/BigtableHBaseSettings.java:42]: Can we add `@VisibleForTesting` and a comment on "this is used to override the default closing timeout of 10 minutes in the test so the test can run faster".

**Review by mutianf — APPROVED** [review]
LGTM after nits.
