### PR TITLE
fix: keep only failed actions in List<Delete>

### LINKED ISSUE #2998: Table#delete(List) should mutate the list in place and remove successful actions
According to
https://hbase.apache.org/1.4/apidocs/org/apache/hadoop/hbase/client/Table.html#delete(java.util.List)

When an error happens, the list should get modified to only include failed deletes

### PR DESCRIPTION
**Pull request by mutianf**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable-hbase/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2998 ☕️

### CODE REVIEW

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java [hunk 1]
```diff
@@ -222,17 +222,23 @@ public void batch(List<? extends Row> actions, @Nullable Object[] results)
...
   /**
    * batch.
    *
    * @param actions a {@link java.util.List} object.
+   * @param removeSucceededActions if true, remove succeeded actions from {@code actions}
    * @return an array of {@link org.apache.hadoop.hbase.client.Result} objects.
    * @throws java.io.IOException if any.
    */
-  public Result[] batch(List<? extends Row> actions) throws IOException {
+  public Result[] batch(List<? extends Row> actions, boolean removeSucceededActions)
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java:237]: Should this be package private?

File: bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java [hunk 2]
```diff
@@ -284,6 +300,14 @@ public void batch(List<? extends Row> actions, @Nullable Object[] results)
         hosts.add(options.getDataHost());
       }
     }
+    if (removeSucceededActions) {
+      for (int i = results.length - 1; i >= 0; i--) {
+        // if result is not null, it succeeded
+        if (results[i] instanceof Result) {
```
Comment (igorbernstein2) [inline bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java:306]: I'm a bit confused by this check. Isnt the result type for a delete a Void? and Result is for Get?

Comment (mutianf) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java:306]: Hmm, I thought it would be an empty result? https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java#L107

I could also check if it's not a throwable

Comment (igorbernstein2) [reply bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java]: I think the later would be better

**Review by igorbernstein2 — APPROVED** [review]
lgtm
